### ISSUE TITLE
gitbucket-windows-backup-plugin導入時のエラー

### ISSUE THREAD

**Issue by Ry0** [jyuch/gitbucket-windows-backup-plugin#7]
gitbucket-windows-backup-pluginのインストール時（Reload pluginを押したあと）に以下のエラーが出ます。
```java
java.io.IOException: Unable to delete file: C:\Users\Ry0\gitbucket\data\plugins\.installed\gitbucket-windows-backup-plugin-assembly-0.6.0.jar
```
gitbucket-windows-backup-plugin使用バージョンは0.6.0です。
gitbucketのバージョンを4.24.0、4.24.1、4.26.0（そもそも未サポート）と試しましたがうまくいきませんでした。
なにかわかることがございましたら、教えていただけませんか

**Comment by jyuch** [comment]
gitbucketを停止させてから`GITBUCKET_HOME\plugins\.installed`の中のgitbucket-windows-backup-pluginのjarファイルを手動で削除して再起動してみてください。

gitbucketはプラグインの動的なリロード機構を備えているのですが、Windows環境ではjarの解放に失敗することがあり、その結果ファイルハンドルを掴みっぱなしになり削除に失敗することがあるようです。

https://github.com/gitbucket/gitbucket/issues/1901

gitbucket本体のissueが解決されるまではプラグインの抜き差しはgitbucketを停止させてから行ったほうが良いかもしれません。
